---
- name: Simple Nginx Deployment
  hosts: all # 또는 AWX 인벤토리의 EC2 그룹 이름 (예: ec2_instances)
  become: yes # sudo 권한으로 실행

  tasks:
    - name: dpkg, apt, debconf 잠금이 없는지 확인하고 정리합니다.
      ansible.builtin.shell: |
        sudo dpkg --configure -a
        sudo rm -f /var/lib/dpkg/lock-frontend
        sudo rm -f /var/lib/dpkg/lock
        sudo rm -f /var/cache/apt/archives/lock
        sudo rm -f /var/cache/debconf/config.dat.tmp
        sudo rm -f /var/cache/debconf/config.dat
        sudo apt clean
        sudo apt update
      args:
        warn: no
      failed_when: false
      changed_when: false

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a basic index.html file
      ansible.builtin.copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Simple Nginx Page</title>
          </head>
          <body>
              <h1>Hello from Nginx on EC2!</h1>
              <p>This page was deployed by Ansible.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'