---
- name: Install Python 3 from Nexus on EC2 Ubuntu
  hosts: ec2-inventory # AWX 인벤토리의 그룹명
  gather_facts: yes #원격 호스트의 정보 수집 여부
  become: yes # EC2에 파일을 배포할 시 권한문제 발생할 경우 sudo 실행

  vars:
    nexus_url: "http://172.17.0.1:8081/repository/test-repo/test/Python-3.13.3.tgz" # Nexus의 python3.tgz 파일 경로
    download_dir: "/tmp/python_install" #EC2 Ubuntu에 임시로 저장하는 경로
    install_dir: "/home/ubuntu" # 실제 Python 을 설치하는 경로
    python_tgz_name: "Python-3.13.3.tgz" # 다운로드할 파일 이름

  tasks:
    - name: EC2에 Python 임시 다운로드
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        mode: '0755'

    - name: Download python3.tgz from Nexus
      ansible.builtin.get_url:
        url: "{{ nexus_url }}"
        dest: "{{ download_dir }}/{{ python_tgz_name }}"
        username: "{{ nexus_username | default(omit) }}" # Nexus Credential에서 가져옴, default(omit) : 변수가 정의되지 않았을 때
        password: "{{ nexus_password | default(omit) }}" # Nexus Credential에서 가져옴
        validate_certs: no # 개발 환경에서는 no로 설정할 수 있지만, 프로덕션에서는 CA 인증서 유효성 검사 필요

    - name: Ensure install directory exists
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'

    - name: Unarchive python3.tgz
      ansible.builtin.unarchive:
        src: "{{ download_dir }}/{{ python_tgz_name }}"
        dest: "{{ install_dir }}"
        remote_src: yes # 원격지에서 다운로드한 파일임을 명시

    - name: Run any necessary setup scripts (if included in the tgz)
      ansible.builtin.shell: |
        tar xvzf Python-3.13.3.tgz
        cd Python-3.13.3.tgz
        ./configure
        make
        sudo make install
        echo "Check if there's a setup script inside {{ install_dir }}"
      args:
        chdir: "{{ install_dir }}"
      when: false # 실제 설치 스크립트가 있다면 true로 변경하고 내용 수정

    - name: Create symbolic link for python3 (if not already in path)
      ansible.builtin.file:
        src: "{{ install_dir }}/bin/python3" # 압축 해제된 python3 실행 파일 경로 확인 필요
        dest: "/usr/local/bin/python3"
        state: link
        force: yes # 기존 링크가 있다면 덮어씁니다.

    - name: Verify Python 3 installation
      ansible.builtin.command: python3 --version
      register: python_version_output
      changed_when: false

    - name: Display Python 3 version
      ansible.builtin.debug:
        msg: "Python 3 installed version: {{ python_version_output.stdout }}"